@startmindmap
skinparam monochrome true
* 现代博客指南
** 博客搭建-1
** SEO优化-2
*** 现状研究
**** 域名研究
**** 流量来源研究
**** 索引研究
**** 关键词研究
**** 竞品研究
**** 内容研究
**** 反向链接研究
*** 优化
**** 博客搭建框架优化对比
**** 站内优化
**** 技术性优化
**** 站外优化
** 订阅推送-3
** 加载速度优化-4
** 推广-5
@endmindmap