@startmindmap
skinparam monochrome true
* SEO
** 站内优化
*** 关键词优化
**** Google关键词提示
**** Adwords keyword planner
**** 长尾关键词
*** 内容优化
**** 内容类型
**** 内容结构
**** 内容角度
*** 导航
*** 标题
*** 图片（Alt）
*** Meta信息
*** 网址
*** 内链优化
** 技术性优化
*** 网站页面结构
*** UX用户体验（提高停留时间）
*** 移动适配
*** 可用性
*** 加载速度
*** 网页索引
*** Canonical（唯一网址）
*** 重复内容检测
*** 404错误页占比
*** 重定向
*** Sitemap.xml
*** Robots.txt
*** 结构化数据
** 站外优化
*** 反向链接
**** 社区推广
**** 社交网站
**** 友情链接
*** 网站权威度
*** 竞品分析
** 监控追踪
*** GA
**** 网页浏览量
**** 跳出率
**** 停留时间
**** 搜索关键词
**** 最受欢迎的页面
**** 退出最多的页面
*** Google Search Console
** 资源工具
*** 资源
*** 工具
**** Chrome SEO Extension
@endmindmap