@startmindmap
skinparam monochrome true
* 广告
** 定义
*** 是付费交流活动
*** 提供信息
*** 游说他人
** 行为
*** 推出/改进品牌
*** 销售产品和服务
** 构成
*** 三方架构
**** 广告主（零售商、生产商、金融公司、慈善机构、政府以及无数类似的人或机构）
***** 为了能迅速实现利润
***** 为了能在未来能继续赢利
**** 媒体（拿走90%利润）
***** 电视（展示广告）
***** 印刷品（展示/分类广告）
***** 海报（展示广告）
***** 电台（展示广告）
***** 电影（展示广告）
***** 互联网（展示/分类广告）
**** 广告代理机构（拿走10%利润）
***** 制作广告
***** 代广告主投放广告
*** 四方架构
**** 广告投放者
**** 媒体
**** 创意代理
**** 媒体代理
** 内容编写技巧
*** 生活方式
*** 认同感
*** 性感
*** 恐惧心理
*** 名人
*** 科学证明
*** 幽默感
*** 比较心理
left side
** 分类
*** 传播媒介为标准
**** 报纸广告
**** 杂志广告
**** 网上广告
**** 电视广告
**** 电影广告
**** 幻灯片广告
**** 包装广告
**** 广播广告
**** 海报广告
*** 招贴广告
*** POP广告
*** 交通广告
*** 电邮广告
** 以广告传播范围为标准
*** 国际性广告
*** 全国性广告
*** 地方性广告
*** 区域性广告
** 以广告传播对象为标准
*** 消费者广告
*** 商业/品牌广告
** 以广告主为标准
*** 一般广告
*** 零售广告
** 以手法、内容为标准
*** 资讯式广告
*** 透导性广告
** 技术手段
*** 反复宣传
*** 信息洪流
*** 质量证明
*** 品牌社团
*** 兑现口号
*** 争论
*** 潜意识养成
@endmindmap