@startmindmap
skinparam monochrome true
* 互联网广告
** 历史
*** 合约广告
*** 广告网络（网盟）
*** 程序化广告
*** 原生广告
** 广告形式
*** 展示广告
**** 网页横幅广告
**** 框架广告
**** Pop-ups/Pop-unders
**** 浮动广告
**** 展开式广告
**** 特技横幅广告
**** Feed流广告
*** 激励广告
*** 插页式广告
*** 文字广告
*** 搜索引擎广告（SEM）
**** 免费搜索广告（SEO）
**** 付费搜索广告
*** 原生广告
**** 信息流广告
**** 文章内嵌广告
**** 匹配内容
*** 付费社交广告
**** Facebook
**** Instagram
**** Snapchat
**** Twitter
**** LinkedIn
*** 移动端广告
*** 电子邮件广告
*** 在线分类广告
*** 再营销广告
*** 视频广告
*** 联盟营销（Affiliate）
*** 内容营销
*** 在线营销平台
*** 广告软件
** 计费方式
*** 按照千人印象费用（CPM）收费
*** 按照每点击成本（CPC）收费
*** 按照每行动成本（CPA）收费
*** 按照每安装成本（CPI）收费
*** 按照每播放成本（CPV）收费
*** 按照每销售成本（CPS）收费
@endmindmap