@startmindmap
skinparam monochrome true
* 市场营销
** 市场
*** 产品
*** 价格
*** 地点
*** 促销
** 营销
*** 4S
*** 满意度
*** 服务
*** 速度
*** 诚意
left side
** 种类
*** 整合营销
**** 线上营销（互联网广告）
**** 线下营销（公车广告/看板/优惠券发放）
*** 数据库营销
*** 网络营销
**** 搜索引擎营销
**** 显示广告营销
**** 电子邮件营销
**** 会员营销
**** 交互式营销
**** 病毒营销
**** 论坛营销
**** 视频营销
**** 博客营销
**** 社群营销
**** 关键字营销
**** SEO营销
**** 原生广告
*** 直效营销
**** 电话营销
**** 电视购物
**** 网络销售
*** 关系营销
*** 口碑营销
right side
** 基本流程
*** 市场机会分析
*** 市场细分
*** 目标市场选择
*** 市场定位
*** 4Ps（生产者为导向的营销组合）
**** 价格price
**** 产品product
**** 促销promotion
**** 地点place
*** 4Cs（消费者为导向的营销组合）
**** 消费者Consumer
**** 成本Cost
**** 交流Communication
**** 便捷Convenience
** 发展阶段
*** 生产导向阶段
*** 产品导向阶段
*** 销售导向阶段
*** 市场导向阶段
*** 社会长远利益导向阶段
@endmindmap