@startmindmap
skinparam monochrome true
* 本地化测试
** 语言相关
*** 术语表
*** 通用短语库
*** 无语法错误
*** 无拼写错误
*** 标点符号
*** 姓名
*** 地点
*** 标题
** 地域与文化
*** 日期时间格式
*** 电话地址格式
*** 货币格式
*** 产品名称
*** 计量单位
*** 颜色
** UI界面
*** 带文字图片
*** 布局一致
*** 连字符和换行符位置
*** 对话框/弹窗/通知
*** 文本长度
** 功能测试
*** 超链接
*** 输入框
*** 快捷键
*** 列表排序
*** 字体
@endmindmap